

/*---
author: Mathias Bynens
esid: sec-names-and-keywords
description: |
  Test that Unicode v15.1.0 ID_Continue characters are accepted as
  identifier part characters.
info: |
  Generated by https://github.com/mathiasbynens/caniunicode
---*/

var _‌‍・･;
