

/*---
author: Mathias Bynens
esid: sec-names-and-keywords
description: |
  Test that Unicode v13.0.0 ID_Continue characters are accepted as
  identifier part characters.
info: |
  Generated by https://github.com/mathiasbynens/caniunicode
---*/

var _୕ඁ꠬ᪿᫀ𐺫𐺬𑇎𑇏𑤰𑤱𑤲𑤳𑤴𑤵𑤷𑤸𑤻𑤼𑤽𑤾𑥀𑥂𑥃𑥐𑥑𑥒𑥓𑥔𑥕𑥖𑥗𑥘𑥙𖿤𖿰𖿱🯰🯱🯲🯳🯴🯵🯶🯷🯸🯹;
